name: Add Stata license
on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:
    inputs:
      stata_version:
        type: choice
        required: true
        description: 'Stata Version:'
        default: '18'
        options:
          - '18'
          - '17'
          - '16'
      stata_serial:
        required: true
        description: 'Stata license serial number:'
      stata_code:
        required: true
        description: 'Stata license code:'
      stata_authorization:
        required: true
        description: 'Stata license authorization:'
      name:
        required: true
        description: 'Full name:'
      institution:
        required: true
        description: 'Institution:'
        default: 'University of Toronto'

jobs:
  install:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Github's default timeout is 6hr, the maximum configurable timeout is 72hr

    steps:
      #######################
      # Configure
      #######################

      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Set Stata version in config
        run: |
          yq eval '.stata_version = ${{ github.event.inputs.stata_version }}' automation/config.yaml -i
          echo "STATA_VERSION=${{ github.event.inputs.stata_version }}" >> $GITHUB_ENV

      - name: Mask Stata license information
        run: |
          stata_code=$(jq -r '.inputs.stata_code' $GITHUB_EVENT_PATH)
          echo "::add-mask::$stata_code"

          stata_authorization=$(jq -r '.inputs.stata_authorization' $GITHUB_EVENT_PATH)
          echo "::add-mask::$stata_authorization"

      - name: Install Stata dependencies from apt
        run: |
          # Install ncurses5 from Ubuntu 22.04 apt repository: still a Stata dependency but no longer available in the 24.04 apt repository
          echo "deb http://archive.ubuntu.com/ubuntu jammy main universe" | sudo tee /etc/apt/sources.list.d/jammy.list
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --yes --no-install-recommends libncurses5 libtinfo5 age
          sudo rm /etc/apt/sources.list.d/jammy.list

      - name: Install Stata license
        run: |
          set +e

          timeout 3m ./automation/stata_install.py --install-source=decrypt --license-source=env --version=${STATA_VERSION} --no-upgrade
          rc=$?

          set -e

          if [ $rc -eq 124 ]; then
            message="<h1>⌛️ Error</h1> The Stata installation timed out after 3 minutes. The most likely problem is that the license information was invalid. Check the logs for more details."
            echo "$message" >> $GITHUB_STEP_SUMMARY
            echo "$message"
          elif grep -q 'License not applicable to this Stata' stata.log; then
            message="<h1>⛔️ Error</h1> The Stata license was not valid for running Stata ${{ github.event.inputs.stata_version }} BE. The most likely problem is that you have a valid license for an earlier version of Stata. You can change the Stata version in the dropdown menu when you re-run the stata_license Github Action."
            echo "$message" >> $GITHUB_STEP_SUMMARY
            echo "$message"
            exit 1
          fi
          exit $rc
        env:
          STATA_AGE_PRIVATE_KEY: ${{ secrets.STATA_AGE_PRIVATE_KEY }}
          stata_serial: ${{ inputs.stata_serial }}
          stata_code: ${{ inputs.stata_code }}
          stata_authorization: ${{ inputs.stata_authorization }}
          name: ${{ inputs.name }}
          institution: ${{ inputs.institution }}

      - name: Store encrypted Stata license in repository
        run: |
          age -r "${STATA_AGE_PUBLIC_KEY}" --output stata.lic.encrypted /usr/local/stata/stata.lic

          git --git-dir .git --work-tree . config user.name github-actions[bot]
          git --git-dir .git --work-tree . config user.email github-actions@github.com
          git --git-dir .git --work-tree . add \
            stata.lic.encrypted \
            automation/config.yaml \
            .devcontainer/devcontainer.json
          git --git-dir .git --work-tree . commit -m "Store encrypted Stata license"
          git --git-dir .git --work-tree . push
        env:
          STATA_AGE_PUBLIC_KEY: ${{ secrets.STATA_AGE_PUBLIC_KEY }}

      - name: Show success message
        run: echo "<h1>✅ Success</h1> Your Stata license was successfully installed in this repository as an encrypted file <code>stata.lic.encrypted</code>." >> $GITHUB_STEP_SUMMARY
        if: success()

      - name: Show failure message
        run: echo "<h1>❌ Failure</h1> Your Stata license could not be installed. Please check the guide (linked in the README) and the logs for more information. Post on the Quercus <b>Course Logistics and Assignment Details</b> discussion board if you're still having trouble." >> $GITHUB_STEP_SUMMARY
        if: failure()
